name: Node Github CI

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.10.0, 10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm test
      env:
        CI: true
  
  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:      
    - name: SSH and deploy node app
      env: 
          SSH_KEY: ${{ secrets.SSH_KEY }}
      uses: appleboy/ssh-action@v0.0.2
      run: |
        touch ~/ssh_key.txt
        echo $SSH_KEY >> ~/ssh_key.txt
      with:
        args: > 
          --host ${{ secrets.SSH_HOST }} --user ${{ secrets.SSH_USER }} -i ~/ssh_key.txt
          --script 'cd ~/sample-node-github'
          --script 'git pull'
          --script 'npm install --production'
          --script 'pm2 restart all'
  