name: Node Github CI

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm test
      env:
        CI: true
  
  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@v0.0.2
      with:
        args: > 
          --host ${{ secrets.NODE_SERVER }} --ssh-key ${{ secrets.SSH_KEY }}
          --script 'cd ~/node-jenkins-test'
          --script 'git pull'
          --script 'npm install --production'
          --script 'pm2 restart all'
  